### PR TITLE
act on remove possibly redundant pull command

### PR DESCRIPTION
**Pull request by asshizu**
This update improves the GitHub Actions workflow by removing unnecessary steps for pulling the servercore Docker image. It simplifies the build process and refines the compression logic to target files within the flip_fluids directory more efficiently. These changes streamline the workflow, reduce runtime, and improve maintainability while keeping artifact generation intact.

### CODE REVIEW

**Comment by asshizu** [comment]
actions seem to be zipping my zip 🤔

**Comment by nroggendorff** [comment]
> actions seem to be zipping my zip 🤔

it was doing that before, too..

**Comment by nroggendorff** [comment]
the question is- is it `actions/upload-artifact` that's doing it, or the builder itself?

**Comment by asshizu** [comment]
I fixed it!

**Comment by nroggendorff** [comment]
good job

**Pull request merged**
